AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'app

  Sample SAM Template for app

  '
Globals:
  Function:
    Timeout: 5
Parameters:
  AppStage:
    Type: String
    Default: api
Resources:
  WebApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName:
        Ref: AppStage
  UploadS3Bucket:
    Type: AWS::S3::Bucket
  ShowFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mnoyes-sam-test-app/17d4e8f27eaa12a14aecc3825c10ccee
      Handler: show-form
      Runtime: go1.x
      Events:
        ShowForm:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: WebApi
  ProcessFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mnoyes-sam-test-app/f6ed91f62516d31c713a014f50e7bd97
      Handler: process-form
      Runtime: go1.x
      Events:
        SubmitForm:
          Type: Api
          Properties:
            Path: /
            Method: post
            RestApiId:
              Ref: WebApi
      Environment:
        Variables:
          UPLOAD_S3_BUCKET:
            Ref: UploadS3Bucket
      Policies:
      - S3FullAccessPolicy:
          BucketName:
            Ref: UploadS3Bucket
  ShowFormErrors:
    Type: AWS::CloudWatch::Alarm
    Properties:
      MetricName: Errors
      Statistic: Sum
      ComparisonOperator: GreaterThanThreshold
      Threshold: 5
      Period: 60
      EvaluationPeriods: 1
      TreatMissingData: notBreaching
      Namespace: AWS/Lambda
      Dimensions:
      - Name: FunctionName
        Value:
          Ref: ShowFormFunction
Outputs:
  UserFormApi:
    Description: API Gateway endpoint URL for Prod environment for First Function
    Value:
      Fn::Sub: https://${WebApi}.execute-api.${AWS::Region}.amazonaws.com/${AppStage}/
  UploadBucket:
    Description: S3 Bucket for user information
    Value:
      Ref: UploadS3Bucket
  ShowFormFunction:
    Description: First Lambda Function ARN
    Value:
      Fn::GetAtt:
      - ShowFormFunction
      - Arn
  ShowFormFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - ShowFormFunctionRole
      - Arn
